version: "2"

volumes:
    plower-data:

services:
  plower-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo-db
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'

  mongo-db:
    image: mongo:4.4.13-focal
    restart: always
    environment:
      MONGO_INITDB_DATABASE: plower
    volumes:
      - 'plower-data:/data/db'
    ports:
      - "27017:27017"
    command: [--auth]
  